### ISSUE TITLE
模型量化问题

### ISSUE THREAD

**Issue by lxn96** [xu-peng-tao/SSD-Pruning-and-quantification#1]
你好，想问一下你模型量化结果的模型大小是怎么得到的，我量化前后保存的pth文件都是180MB。

**Comment by xu-peng-tao** [comment]
因为实际上量化后保存的pth文件权重依然会是全精度的（即把量化权重保存成全精度浮点数），只有实际部署的时候才会应用真正量化权重，可以用get_model_size.py得到量化模型大小

**Comment by xu-peng-tao** [comment]
感谢关注
