### ISSUE TITLE
权重文件链接失效

### ISSUE THREAD

**Issue by zrx11** [xu-peng-tao/SSD-Pruning-and-quantification#2]
您好，/pretrained/download中权重文件的网盘链接均已失效，能否再次上传，万分感谢！

**Comment by xu-peng-tao** [comment]
感谢您的关注，您现在看看，应该可以了

**Comment by zrx11** [comment]
> 感谢您的关注，您现在看看，应该可以了

非常感谢您的回复，除了vgg_bn_ssd300_voc0712_model_final.pth链接的提取码错误，其他链接均能下载了，再次感谢！

**Comment by Chang851110** [comment]
Excuse me , could you send the pretrained weight to me 
Because I can't download the pretrained.
me email : kevin97563@gmail.com
